language: go

go:
  - 1.5
  - 1.6
  - 1.7.x
  - 1.8.x
  - tip

install:
  - go get -t -v . ./pry

before_install:
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=pry.coverprofile ./pry
  - go test -v -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile
