language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

install:
  - go get -t -v . ./pry ./generate ./playground/server

before_install:
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v -race -coverprofile=pry.coverprofile ./pry
  - go test -v -race -coverprofile=generate.coverprofile ./generate
  - go test -v -race -coverprofile=main.coverprofile
  - go test -v -race -coverprofile=server.coverprofile ./playground/server
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile
